/**
 * The stdio MCP shim that `agy` spawns, and the code that installs it.
 *
 * Why a shim at all, rather than registering the bridge's own HTTP endpoint with
 * `agy mcp add -t http pix3 http://127.0.0.1:8484/…`:
 *
 *   1. **The token.** `-H 'x-pix3-mcp-token: …'` would write a secret into
 *      `~/.gemini/config/mcp_config.json` — a second plaintext copy, in a file this bridge does not
 *      own and the Antigravity IDE may sync.
 *   2. **Which session is calling.** Several `agy` processes would hit one URL and `tools/call`
 *      would arrive with nothing to tie it to a chat. Correlating by timing is not sound: measured,
 *      agy connects its MCP servers EAGERLY at process start, long before the model asks for
 *      anything.
 *
 * A stdio server is spawned as a child of `agy`, so it inherits agy's environment — and the bridge
 * sets that environment per spawn. Measured live: a shim registered this way saw
 * `PIX3_BRIDGE_SESSION` exactly as the bridge set it on the `agy` process. So the shim is a ~120
 * line, dependency-free pipe: NDJSON JSON-RPC in on stdin → `POST /agents/agy/mcp/:sessionId` →
 * answer out on stdout.
 *
 * Protocol notes, all from a live capture (agy 1.2.5):
 *   - agy sends a NON-STANDARD `server/discover` request BEFORE `initialize`. A shim that rejects
 *     unknown methods never gets to `initialize`, so unknown requests get an empty result.
 *   - it advertises `protocolVersion: 2025-11-25` and accepts an older one back.
 *   - a `tools/call` can sit for as long as a human takes to answer in the editor, so the shim emits
 *     `notifications/progress` while it waits rather than relying on agy's (unmeasured) timeout.
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

/** Where the shim is installed. A stable path beats an npx cache that can be garbage-collected. */
export const agyShimPath = (): string => path.join(os.homedir(), '.pix3', 'agy-mcp-shim.mjs');

/**
 * Bumped whenever {@link SHIM_SOURCE} changes so an installed copy from an older bridge is
 * rewritten instead of silently serving a stale protocol.
 */
export const SHIM_VERSION = 2;

const SHIM_SOURCE = `#!/usr/bin/env node
// Generated by @pix3/agent-bridge — do not edit. Reinstall with: pix3-agent-bridge agy setup
// shim-version: ${SHIM_VERSION}
//
// Bridges agy's stdio MCP transport to the bridge's per-session tool relay. Every editor tool call
// agy makes is forwarded to POST \${PIX3_BRIDGE_MCP_URL}/\${PIX3_BRIDGE_SESSION} and its answer is
// written back on stdout. The token and the session id arrive in this process's environment, set by
// the bridge on the agy process this shim is a child of.

const SESSION = process.env.PIX3_BRIDGE_SESSION ?? '';
const URL_BASE = process.env.PIX3_BRIDGE_MCP_URL ?? '';
const TOKEN = process.env.PIX3_BRIDGE_MCP_TOKEN ?? '';
const PROGRESS_INTERVAL_MS = 15000;

const write = (message) => {
  process.stdout.write(JSON.stringify(message) + '\\n');
};

const reply = (id, result) => write({ jsonrpc: '2.0', id, result });
const fail = (id, message) => write({ jsonrpc: '2.0', id, error: { code: -32000, message } });

const post = async (method, params) => {
  if (!SESSION || !URL_BASE) throw new Error('The pix3 bridge did not pass a session to this shim.');
  const response = await fetch(\`\${URL_BASE}/\${encodeURIComponent(SESSION)}\`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-pix3-mcp-token': TOKEN },
    body: JSON.stringify({ method, params }),
  });
  if (!response.ok) {
    const text = await response.text().catch(() => '');
    throw new Error(\`bridge returned HTTP \${response.status}\${text ? \`: \${text.slice(0, 300)}\` : ''}\`);
  }
  return response.json();
};

// Requests still waiting on the bridge. stdin closing must not cut one short: a tool call can be
// mid-flight (the editor is running it) exactly when agy is shutting the transport down, and exiting
// there would look to agy like the tool silently failed.
let inFlight = 0;
let inputClosed = false;
const exitWhenDrained = () => {
  if (inputClosed && inFlight === 0) process.exit(0);
};

const handle = async (message) => {
  const { id, method, params } = message;
  if (id === undefined || id === null) return; // notification — nothing to answer
  inFlight += 1;
  try {
    if (method === 'initialize') {
      reply(id, {
        protocolVersion: params?.protocolVersion ?? '2025-06-18',
        capabilities: { tools: {} },
        serverInfo: { name: 'pix3', version: '${SHIM_VERSION}.0.0' },
      });
      return;
    }
    if (method === 'tools/list') {
      reply(id, await post('tools/list', {}));
      return;
    }
    if (method === 'tools/call') {
      // The editor may take a while (a slow tool, a human watching). Keep agy informed rather than
      // letting it decide on its own that we are gone.
      const progressToken = params?._meta?.progressToken;
      const ticker = progressToken
        ? setInterval(() => {
            write({
              jsonrpc: '2.0',
              method: 'notifications/progress',
              params: { progressToken, progress: 0, message: 'waiting for the pix3 editor' },
            });
          }, PROGRESS_INTERVAL_MS)
        : null;
      try {
        reply(id, await post('tools/call', { name: params?.name, arguments: params?.arguments ?? {} }));
      } finally {
        if (ticker) clearInterval(ticker);
      }
      return;
    }
    // Unknown request (agy sends 'server/discover' before initialize): answer, never reject.
    reply(id, {});
  } catch (error) {
    fail(id, error instanceof Error ? error.message : String(error));
  } finally {
    inFlight -= 1;
    exitWhenDrained();
  }
};

let buffer = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
  buffer += chunk;
  let newline;
  while ((newline = buffer.indexOf('\\n')) >= 0) {
    const line = buffer.slice(0, newline).trim();
    buffer = buffer.slice(newline + 1);
    if (!line) continue;
    let message;
    try {
      message = JSON.parse(line);
    } catch {
      continue;
    }
    void handle(message);
  }
});
process.stdin.on('end', () => {
  inputClosed = true;
  exitWhenDrained();
});
`;

export interface ShimInstallResult {
  readonly path: string;
  readonly written: boolean;
}

/**
 * Write the shim to its stable path if it is missing or out of date. Idempotent, so the server can
 * call it on every boot and `agy setup` can call it again.
 */
export const installShim = (): ShimInstallResult => {
  const target = agyShimPath();
  try {
    if (fs.readFileSync(target, 'utf8') === SHIM_SOURCE) return { path: target, written: false };
  } catch {
    /* missing or unreadable — (re)write it */
  }
  fs.mkdirSync(path.dirname(target), { recursive: true, mode: 0o700 });
  fs.writeFileSync(target, SHIM_SOURCE, 'utf8');
  return { path: target, written: true };
};
