/**
 * Type libraries and compiler options fed to the in-editor Monaco TypeScript
 * worker so that user scripts get real IntelliSense against the engine.
 *
 * The runtime is shipped to the browser as raw TS *sources* (not generated
 * `.d.ts`) via `import.meta.glob(..., '?raw')` — the same mechanism
 * `PlayableHtmlBuildService` already uses, so Vite dedupes the modules and
 * there is ~zero marginal bundle cost and no separate build step to keep in
 * sync during `npm run dev`. `@pix3/runtime`'s own `package.json` declares
 * `"types": "./src/index.ts"`, i.e. source-as-types is this package's contract.
 *
 * This module has NO runtime dependency on `monaco-editor` (the `monaco`
 * instance is passed in), so it stays cheap to import and easy to unit-test.
 */

import type * as Monaco from 'monaco-editor';

/** A virtual file registered with the TS worker. */
export interface MonacoLib {
  /** Virtual `file:///…` path used for module resolution. */
  readonly filePath: string;
  readonly content: string;
}

// Runtime TypeScript sources. Same glob shape as PlayableHtmlBuildService so
// Vite emits the modules once and reuses them here.
const RUNTIME_SOURCE_LOADERS = import.meta.glob(
  [
    '../../../packages/pix3-runtime/src/**/*.ts',
    '../../../packages/pix3-runtime/src/**/*.js',
    '../../../packages/pix3-runtime/src/**/*.json',
  ],
  { query: '?raw', import: 'default' }
) as Record<string, () => Promise<string>>;

// three.js type declarations (three itself ships none; @types/three does).
// Registered under `file:///node_modules/three/**` so the bare `three`
// specifier and `three/examples/*` subpaths resolve.
const THREE_TYPE_LOADERS = import.meta.glob('../../../node_modules/@types/three/**/*.d.ts', {
  query: '?raw',
  import: 'default',
}) as Record<string, () => Promise<string>>;

/**
 * Ambient declarations for modules that either have no shipped types
 * (`ios-haptics`, shimmed at runtime by `runtime-import-map.ts`) or are esbuild
 * asset-import specifiers that would otherwise raise TS2307 on the user's own
 * file.
 */
const EDITOR_AMBIENT_SHIMS = `// Generated by Pix3 — ambient shims for the in-editor code editor.
declare module 'ios-haptics' {
  interface Haptic {
    (): void;
    confirm(): void;
    error(): void;
  }
  export const haptic: Haptic;
  const _default: { haptic: Haptic };
  export default _default;
}
declare module '*?raw' {
  const content: string;
  export default content;
}
declare module '*?url' {
  const url: string;
  export default url;
}
declare module '*.css' {
  const content: string;
  export default content;
}
declare module '*.glsl' {
  const content: string;
  export default content;
}
declare module '*.frag' {
  const content: string;
  export default content;
}
declare module '*.vert' {
  const content: string;
  export default content;
}
`;

/** Fixed virtual path of the generated scene-node names lib (Part 2). */
export const SCENE_NODES_LIB_PATH = 'file:///pix3/generated/scene-nodes.d.ts';

/** Fixed virtual path of the ambient shims lib. */
export const EDITOR_AMBIENT_LIB_PATH = 'file:///pix3/generated/editor-ambient.d.ts';

const remapAfter = (key: string, marker: string, prefix: string): string => {
  const index = key.indexOf(marker);
  const relative = index >= 0 ? key.slice(index + marker.length) : key;
  return `${prefix}${relative}`;
};

/**
 * Fetch and remap all static engine/vendor type libraries. Returns virtual
 * files ready to hand to `typescriptDefaults.addExtraLib`. Fetched lazily —
 * only called the first time a code tab opens (Monaco itself is lazy-loaded).
 */
export async function loadMonacoRuntimeLibs(): Promise<MonacoLib[]> {
  const [runtime, three] = await Promise.all([
    Promise.all(
      Object.entries(RUNTIME_SOURCE_LOADERS).map(async ([key, load]) => ({
        filePath: remapAfter(key, 'packages/pix3-runtime/', 'file:///node_modules/@pix3/runtime/'),
        content: await load(),
      }))
    ),
    Promise.all(
      Object.entries(THREE_TYPE_LOADERS).map(async ([key, load]) => ({
        filePath: remapAfter(key, '@types/three/', 'file:///node_modules/three/'),
        content: await load(),
      }))
    ),
  ]);

  return [
    ...runtime,
    ...three,
    { filePath: EDITOR_AMBIENT_LIB_PATH, content: EDITOR_AMBIENT_SHIMS },
  ];
}

/**
 * Compiler options for the TS worker, mirroring the esbuild settings in
 * `ScriptCompilerService` (target es2022, ESM). `strict` is intentionally OFF
 * so existing scripts — which esbuild never type-checked — don't suddenly
 * flood with errors; semantic diagnostics stay on so genuine mistakes (wrong
 * method names, bad argument types, misspelled imports) still surface.
 */
export function createCompilerOptions(monaco: typeof Monaco): Monaco.typescript.CompilerOptions {
  const ts = monaco.typescript;
  return {
    // Monaco's bundled ScriptTarget has no ES2022 member; ESNext is permissive
    // (no downleveling) and correct for diagnostics-only use.
    target: ts.ScriptTarget.ESNext,
    lib: ['es2022', 'dom', 'dom.iterable'],
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.NodeJs,
    baseUrl: 'file:///',
    paths: {
      '@pix3/runtime': ['node_modules/@pix3/runtime/src/index'],
      three: ['node_modules/three/src/Three.Core'],
      'three/*': ['node_modules/three/*'],
    },
    strict: false,
    noImplicitAny: false,
    strictNullChecks: false,
    experimentalDecorators: true,
    useDefineForClassFields: true,
    allowNonTsExtensions: true,
    allowJs: true,
    skipLibCheck: true,
    isolatedModules: true,
    resolveJsonModule: true,
  };
}
